version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes:
      - .:/app
      - sqlite_data:/app/db
    command: >
      sh -c "python project/manage.py migrate &&
             python project/manage.py collectstatic --noinput &&
             python project/manage.py runserver 0.0.0.0:8000"

volumes:
  sqlite_data:
