name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          SUPABASE_DB_HOST: ${{ secrets.DB_HOST }}
          SUPABASE_DB_NAME: ${{ secrets.DB_NAME }}
          SUPABASE_DB_USER: ${{ secrets.DB_USER }}
          SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
        run: |
          python project/manage.py test --verbosity=2

      - name: Run migrations
        if: success()
        env:
          SUPABASE_DB_HOST: ${{ secrets.DB_HOST }}
          SUPABASE_DB_NAME: ${{ secrets.DB_NAME }}
          SUPABASE_DB_USER: ${{ secrets.DB_USER }}
          SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
        run: |
          python project/manage.py migrate
